
CREATE TABLE "SEUNGJUN"."BOARD" (	
    "BOARD_NUMBER" VARCHAR2(100 BYTE), 
    "USER_ID" VARCHAR2(50 BYTE), 
    "SUBJECT" VARCHAR2(150 BYTE), 
    "BOARD_CONTENT" VARCHAR2(255 BYTE), 
    "WRITE_DATE" DATE, 
    CONSTRAINT "BOARD_ID_FK" FOREIGN KEY ("USER_ID")
    REFERENCES "SEUNGJUN"."USERS" ("ID") ON DELETE CASCADE ENABLE
);

CREATE TABLE "SEUNGJUN"."USERS" (	
    "ID" VARCHAR2(20 BYTE), 
    "PWD" VARCHAR2(20 BYTE), 
    "NAME" VARCHAR2(20 BYTE), 
    "EMAIL" VARCHAR2(20 BYTE), 
    "BIRTHDAY" VARCHAR2(20 BYTE), 
    "PHONE" VARCHAR2(15 BYTE), 
    "SEX" NUMBER DEFAULT 1, 
    "REGDATE" DATE DEFAULT sysdate, 
    PRIMARY KEY ("ID")
);

CREATE TABLE "SEUNGJUN"."CART" (	
    "USER_ID" VARCHAR2(100 BYTE), 
    "PRODUCT_CODE" VARCHAR2(100 BYTE), 
    "PRODUCT_OPTION" VARCHAR2(10 BYTE), 
    "PRODUCT_COUNT" VARCHAR2(10 BYTE), 
    "PRODUCT_PRICE" VARCHAR2(100 BYTE), 
    CONSTRAINT "USER_ID_FK" FOREIGN KEY ("USER_ID")
    REFERENCES "SEUNGJUN"."USERS" ("ID") ON DELETE CASCADE ENABLE, 
    CONSTRAINT "PRODUCT_CODE_FK" FOREIGN KEY ("PRODUCT_CODE")
    REFERENCES "SEUNGJUN"."PRODUCTINFORMATION" ("PRODUCTCODE") ON DELETE CASCADE ENABLE
);
   
   
CREATE TABLE "SEUNGJUN"."ORDERS" (	
    "PRODUCTORDERSCODE" VARCHAR2(30 BYTE), 
    "PRODUCTCODE" VARCHAR2(40 BYTE), 
    "USERID" VARCHAR2(20 BYTE), 
    "ORDERSNAME" VARCHAR2(20 BYTE), 
    "FRODUCTNAME" VARCHAR2(100 BYTE), 
    "ORDERQNANTITY" NUMBER(5,0), 
    "FORDUCTPRICE" NUMBER(38,0), 
    "RECIPIENTNAME" VARCHAR2(50 BYTE), 
    "RECIPIENTPHONE" VARCHAR2(20 BYTE), 
    "SHIPPINGADDRESS" VARCHAR2(500 BYTE), 
    "FORWARDINGMESSAGEINABSENCE" VARCHAR2(300 BYTE), 
    "PAYMENTMETHOD" VARCHAR2(200 BYTE), 
    "PAYMENTTIME" DATE, 
    "PRODUCT_OPTION" VARCHAR2(50 BYTE), 
     PRIMARY KEY ("PRODUCTORDERSCODE")
 );
    
CREATE TABLE "SEUNGJUN"."PRODUCTINFORMATION" 
(	
"PRODUCTCODE" VARCHAR2(40 BYTE), 
"PRODUCTTPYE" VARCHAR2(50 BYTE), 
"PRODUCTNAME" VARCHAR2(100 BYTE), 
"PRODCUTPRICE" NUMBER(10,0), 
"THEDELIVERYCHARGE" NUMBER(5,0), 
"PRODUCTDELIVERYDATE" NUMBER(5,0), 
"PRODUCTCLASSIFICATION" VARCHAR2(50 BYTE), 
PRIMARY KEY ("PRODUCTCODE")
);

CREATE SEQUENCE  "SEUNGJUN"."BOARD_NUMBER"  MINVALUE 1 MAXVALUE 999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


CREATE SEQUENCE  "SEUNGJUN"."ORDER_NUMBER"  MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 START WITH 12 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

